global:
  scrape_interval: 30s
  evaluation_interval: 30s
  external_labels:
    cluster: 'aws-ecs'
    replica: 'prometheus-1'

# Short retention since Thanos handles long-term storage
storage:
  tsdb:
    retention.time: 2h
    retention.size: 1GB
    wal-compression: true

# Recording rules for performance optimization
rule_files:
  - "recording_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s
    scrape_timeout: 10s

  - job_name: 'yace'
    static_configs:
      - targets: ['localhost:5000']
    metrics_path: /metrics
    scrape_interval: 60s
    scrape_timeout: 30s
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'aws_lambda_.*'
        target_label: __tmp_keep_metric
        replacement: 'true'
      - source_labels: [__tmp_keep_metric]
        regex: 'true'
        action: keep

  - job_name: 'thanos-sidecar'
    static_configs:
      - targets: ['localhost:10902']
    metrics_path: /metrics
    scrape_interval: 30s

  - job_name: 'thanos-query'
    static_configs:
      - targets: ['localhost:10903']
    metrics_path: /metrics
    scrape_interval: 30s

# Query optimization
query_log_file: /var/log/prometheus/query.log